package javaassignment;

import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Khoo Guo Hao
 */
public class LecturerViewAndWriteFeedback extends FrameFormat {
    private String appointID;
    private String sessionUserID;
    /**
     * Creates new form LecturerViewAndWriteFeedback
     */
    public LecturerViewAndWriteFeedback() {
        initComponents();
    }
    
    public LecturerViewAndWriteFeedback(String sessionUserID, String [] appointmentData) {
        initComponents();
        super.formatWindow("Appointment Details (Feedbacks)");
        this.sessionUserID = sessionUserID;
        studentIDField.setText(appointmentData[3]);
        studentNameField.setText(appointmentData[4]);
        emailField.setText(appointmentData[7]);
        dateField.setText(appointmentData[1]);
        timeSlotField.setText(appointmentData[2]);
        if (appointmentData[5].equals("null")) {
            studentTextArea.setText("<no feedback provided yet>");
        } else {
            studentTextArea.setText(appointmentData[5]);
        }
        if (appointmentData[6].equals("null")) {
            lecturerTextArea.setText("<no feedback provided yet>");
        } else {
            lecturerTextArea.setText(appointmentData[6]);
        }
        appointID = appointmentData[0];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultType = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        studentIDField = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studentNameField = new javax.swing.JLabel();
        dateField = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        timeSlotField = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lecturerTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        studentTextArea = new javax.swing.JLabel();
        saveFeedback = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        emailField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resultType.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        resultType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultType.setText("Appointment Details and Feedback");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Student ID :");

        studentIDField.setBackground(new java.awt.Color(255, 255, 255));
        studentIDField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studentIDField.setForeground(new java.awt.Color(0, 0, 0));
        studentIDField.setOpaque(true);
        studentIDField.setBorder(new EmptyBorder(3, 8, 3, 8));

        jLabel2.setText("Student Name :");

        studentNameField.setBackground(new java.awt.Color(255, 255, 255));
        studentNameField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studentNameField.setForeground(new java.awt.Color(0, 0, 0));
        studentNameField.setText("<html></html>");
        studentNameField.setOpaque(true);
        studentNameField.setBorder(new EmptyBorder(3, 8, 3, 8));

        dateField.setBackground(new java.awt.Color(255, 255, 255));
        dateField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateField.setForeground(new java.awt.Color(0, 0, 0));
        dateField.setOpaque(true);
        dateField.setBorder(new EmptyBorder(3, 8, 3, 8));

        jLabel3.setText("Date :");

        timeSlotField.setBackground(new java.awt.Color(255, 255, 255));
        timeSlotField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timeSlotField.setForeground(new java.awt.Color(0, 0, 0));
        timeSlotField.setOpaque(true);
        timeSlotField.setBorder(new EmptyBorder(3, 8, 3, 8));

        jLabel4.setText("Time Slot :");

        lecturerTextArea.setColumns(20);
        lecturerTextArea.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lecturerTextArea.setRows(5);
        lecturerTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lecturerTextAreaMousePressed(evt);
            }
        });
        lecturerTextArea.setLineWrap(true);
        lecturerTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(lecturerTextArea);

        jLabel5.setText("Your Feedback and Advice :");

        jLabel6.setText("Student Feedback & Comment :");

        studentTextArea.setBackground(new java.awt.Color(255, 255, 255));
        studentTextArea.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        studentTextArea.setForeground(new java.awt.Color(0, 0, 0));
        studentTextArea.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studentTextArea.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        studentTextArea.setOpaque(true);
        studentTextArea.setBorder(new EmptyBorder(5, 8, 5, 8));

        saveFeedback.setText("Save");
        saveFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFeedbackActionPerformed(evt);
            }
        });

        jLabel7.setText("Student Email :");

        emailField.setBackground(new java.awt.Color(255, 255, 255));
        emailField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emailField.setForeground(new java.awt.Color(0, 0, 0));
        emailField.setText("<html></html>");
        emailField.setOpaque(true);
        emailField.setBorder(new EmptyBorder(3, 8, 3, 8));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(resultType, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(saveFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(studentIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(23, 23, 23)
                                .addComponent(studentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(timeSlotField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(23, 23, 23)
                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultType, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentIDField, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateField, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(timeSlotField, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveFeedback))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new LecturerViewFeedbackList(sessionUserID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFeedbackActionPerformed
        // TODO add your handling code here:
        String feedback = lecturerTextArea.getText();
        if (feedback.equals("") || feedback.length() < 4) {
            JOptionPane.showMessageDialog(null, "Invalid feedback cannot be saved.", "Invalid Input", 0);
        } else if (feedback.length() > 100) {
            JOptionPane.showMessageDialog(null, "Feedback is too long.", "Invalid Input", 0);
        } else {
            int confirmation = JOptionPane.showConfirmDialog(
                null, 
                "<html>Are you sure you to save your feedback?</html>", 
                "Confirm Action", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE
            );

            switch (confirmation) {
                case JOptionPane.YES_NO_OPTION -> {
                    control saveFeedback = new control();
                    try {
                        saveFeedback.update(appointID, feedback, "lecturerFeedback");
                        JOptionPane.showMessageDialog(null, "<html>Your feedback is saved.<br>It will be viewable by students.</html>", "Update Message", 1);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "Feedback is too long.", "", 0);
                    } 
                }
                default -> {}
            }
        }
    }//GEN-LAST:event_saveFeedbackActionPerformed

    private void lecturerTextAreaMousePressed(java.awt.event.MouseEvent evt) {
        if (lecturerTextArea.getText().trim().equals("<no feedback provided yet>")) {
            lecturerTextArea.setText("");
            System.out.println("hello");
        } else {
            System.out.println("hi");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerViewAndWriteFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerViewAndWriteFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerViewAndWriteFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerViewAndWriteFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecturerViewAndWriteFeedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateField;
    private javax.swing.JLabel emailField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea lecturerTextArea;
    private javax.swing.JLabel resultType;
    private javax.swing.JButton saveFeedback;
    private javax.swing.JLabel studentIDField;
    private javax.swing.JLabel studentNameField;
    private javax.swing.JLabel studentTextArea;
    private javax.swing.JLabel timeSlotField;
    // End of variables declaration//GEN-END:variables
}
