package javaassignment;

import java.io.*;
import javax.swing.border.EmptyBorder;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.*;
/**
 *
 * @author Khoo Guo Hao
 */
public class ManageReschedule extends FrameFormat {
    private String sessionUserID;
    private String [] columnName = {"Date", "Time Slot", "Student ID"};
    private DefaultTableModel model = new DefaultTableModel();
    private int row = -1;
    List<String> appID = new ArrayList<>();
    /**
     * Creates new form ManageReschedule
     */
    public ManageReschedule(String sessionUserID) {
        model.setColumnIdentifiers(columnName);
        initComponents();
        this.sessionUserID = sessionUserID;
        super.formatWindow("Manage Reschedules Page");
        loadAppointmentTable();
    }
    
    public void loadAppointmentTable() {
        try (BufferedReader appointBR = new BufferedReader(new FileReader("appointment.txt"))) {
            int counter = 0;
            String eachLine;
            while ((eachLine = appointBR.readLine()) != null) {
                String [] appointDetails = eachLine.split(",");
                String lecturerID = appointDetails[2];
                String status = appointDetails[8];

                String year = appointDetails[3];
                String month = appointDetails[4];
                String day = appointDetails[5];
                
                System.out.println(lecturerID);
                //remember change to sessionUserID
                if (lecturerID.equals(sessionUserID) && status.equals("waiting")) {
                    String date = year+"-"+month+"-"+day;
                    String start = appointDetails[6].substring(0, 2)+":"+appointDetails[6].substring(2);
                    String end = appointDetails[7].substring(0, 2)+":"+appointDetails[7].substring(2);
                    if (appointDetails[9].equals("null")) {
                        
                    }
                    String [] newData = {date, start+" - "+end, appointDetails[1]};
                    model.addRow(newData);
                    appID.add(appointDetails[0]);
                }
                counter++;
            }
            
        } catch (FileNotFoundException ex) {
            try {
                new File("appointment.txt").createNewFile();
            } catch (IOException ex1) {
            } finally {
                JOptionPane.showMessageDialog(null, "An error occured. Try again later.", "Database Failure", 0);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "An error occured. Try again later.", "Database Failure", 0);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        approveButton = new javax.swing.JButton();
        rejectButton = new javax.swing.JButton();
        studentIDField = new javax.swing.JLabel();
        timeSlotField = new javax.swing.JLabel();
        dateField = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainTable.setModel(model);
        mainTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mainTableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(mainTable);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        pack();

        jPanel2.setOpaque(false);

        jLabel1.setText("Student ID");

        jLabel2.setText("Date");

        jLabel3.setText("Time Slot");

        approveButton.setText("Approve");
        approveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveButtonActionPerformed(evt);
            }
        });

        rejectButton.setText("Reject");
        rejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectButtonActionPerformed(evt);
            }
        });

        studentIDField.setBackground(new java.awt.Color(255, 255, 255));
        studentIDField.setBorder(new EmptyBorder(3, 8, 3, 8));
        studentIDField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studentIDField.setForeground(new java.awt.Color(0, 0, 0));
        studentIDField.setOpaque(true);

        timeSlotField.setBackground(new java.awt.Color(255, 255, 255));
        timeSlotField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timeSlotField.setForeground(new java.awt.Color(0, 0, 0));
        timeSlotField.setOpaque(true);
        timeSlotField.setBorder(new EmptyBorder(3, 8, 3, 8));

        dateField.setBackground(new java.awt.Color(255, 255, 255));
        dateField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateField.setForeground(new java.awt.Color(0, 0, 0));
        dateField.setOpaque(true);
        dateField.setBorder(new EmptyBorder(3, 8, 3, 8));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentIDField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(approveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(timeSlotField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeSlotField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(approveButton)
                    .addComponent(rejectButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Rescheduled Appointments");

        infoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        infoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel.setText("Pick a student from table to manage reschedule.");
        infoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(69, 69, 69)
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(154, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void approveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveButtonActionPerformed
        // TODO add your handling code here:
        if (row != -1) {
            int confirmation = JOptionPane.showConfirmDialog(
                null, 
                "Are you sure to approve this reschedule request?", 
                "Confirm Action", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE
            );

            switch (confirmation) {
                case JOptionPane.YES_OPTION -> {
                    String selectedAppID = String.valueOf(appID.get(row));
                    control setApproveInFile = new control();
                    try {
                        setApproveInFile.update(selectedAppID, "accept", "acceptance");
                        JOptionPane.showMessageDialog(null, "<html>Reschedule approved.<br>Saved as upcoming appointment.</html>", "Update Message", 1);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "<html>An error occured.<br>Try again later</html>", "Database Error", 0);
                    }
                }
                default -> {}
            }
        } else {
            JOptionPane.showMessageDialog(null, "<html>You did not select a<br>student from the table.</html>", "Error", 0);
        }
    }//GEN-LAST:event_approveButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new LecturerHomePage(sessionUserID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectButtonActionPerformed
        // TODO add your handling code here:
        if (row != -1) {
            int confirmation = JOptionPane.showConfirmDialog(
                null, 
                "Are you sure to reject this reschedule request?", 
                "Confirm Action", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE
            );

            switch (confirmation) {
                case JOptionPane.YES_OPTION -> {
                    String selectedAppID = String.valueOf(appID.get(row));
                    control setApproveInFile = new control();
                    try {
                        setApproveInFile.cancel_app(selectedAppID);
                        JOptionPane.showMessageDialog(null, "<html>Reschedule rejected.</html>", "Update Message", 1);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "<html>An error occured.<br>Try again later</html>", "Database Error", 0);
                    }
                }
                default -> {}
            }
        } else {
            JOptionPane.showMessageDialog(null, "<html>You did not select a<br>student from the table.</html>", "Error", 0);
        }
    }//GEN-LAST:event_rejectButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    private void mainTableMouseReleased(java.awt.event.MouseEvent evt) {
        row = mainTable.getSelectedRow();
        System.out.println(row);
        String date = String.valueOf(model.getValueAt(row, 0));
        String timeSlot = String.valueOf(model.getValueAt(row, 1));
        String studentID = String.valueOf(model.getValueAt(row, 2));
        
        studentIDField.setText(studentID);
        dateField.setText(date);
        timeSlotField.setText(timeSlot);
        infoLabel.setText("Approve or Reject reschedule request.");
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageReschedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageReschedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageReschedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageReschedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageReschedule("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveButton;
    private javax.swing.JLabel dateField;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mainTable;
    private javax.swing.JButton rejectButton;
    private javax.swing.JLabel studentIDField;
    private javax.swing.JLabel timeSlotField;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
