package javaassignment;
import java.io.*;
import javax.swing.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class view_lecture extends control {
    private String ID;
    
    control available = new control();
    control all = new control();
    
    private JButton[] btn;
    private String[] lecture;
    private String[] lec_id;
    
    private JButton[] btn1;
    private String[] lecture1;
    private String[] lec_id1;
    
    private void passid(int index, String[] id) throws IOException{
        stu_lecture gui = new stu_lecture(id[index], "book", null, ID);
        gui.setVisible(true);
        this.dispose();
    }
    
    public view_lecture(){
        
    }
    
    public view_lecture(String ID) throws IOException {
        initComponents();
        formatWindow("View Lecture Page");
        this.ID = ID;
        Calendar cl = Calendar.getInstance();

        //All
        String[] status = read_AT("status");
        ArrayList<Integer> index_AT = new ArrayList<>();
        for(int i = 0; i < status.length; i++){
            if(status[i].equals("unbooked")){
                index_AT.add(i);
            }
        }

        String[] lec = new String[index_AT.size()];
        String[] y1 = new String[index_AT.size()];
        String[] m1 = new String[index_AT.size()];
        String[] d1 = new String[index_AT.size()];
        String[] at_s = new String[index_AT.size()];
        String[] at_e = new String[index_AT.size()];
        for(int i = 0; i < index_AT.size(); i++){
            lec[i] = read_AT("lec_id")[index_AT.get(i)];
            y1[i] = read_AT("year")[index_AT.get(i)];
            m1[i] = read_AT("month")[index_AT.get(i)];
            d1[i] = read_AT("day")[index_AT.get(i)];
            at_s[i] = read_AT("at_start")[index_AT.get(i)];
            at_e[i] = read_AT("at_end")[index_AT.get(i)];
        }
        int[] year = to_int(y1);
        int[] month = to_int(m1);
        int[] day = to_int(d1);
        int[] at_start = to_int(at_s);
        int[] at_end = to_int(at_e);


        String[] li = read_lec("lec_id");
        String[] ln = read_lec("username");

        //Available Now
        int c_time = Integer.parseInt(String.valueOf(cl.get(Calendar.HOUR_OF_DAY)) + String.valueOf(cl.get(Calendar.MINUTE)));
        int c_year = cl.get(Calendar.YEAR);
        int c_month = cl.get(Calendar.MONTH) + 1;
        int c_day = cl.get(Calendar.DAY_OF_MONTH);

        ArrayList<String> li_s = new ArrayList<>();
        ArrayList<String> ln_s = new ArrayList<>();
        for(int i = 0; i < li.length; i++){
            int x = 0;
            for(int j = 0; j < lec.length; j++){
                if(li[i].equals(lec[j]) && c_year == year[j] && c_month == month[j] && c_day == day[j] && c_time > at_start[j] && c_time < at_end[j]){
                    x = 1;
                }
            }
            if(x == 1){
                li_s.add(li[i]);
                ln_s.add(ln[i]);
            }
        }

        JButton buttons[] = {jButton1, jButton2, jButton3, jButton4};
        if(li_s.isEmpty()){
            jLabel3.setText("No Available Lecture Now");
            for(JButton button : buttons){
                remove(button);
            }
            right.setVisible(false);
            left.setVisible(false);
        }else{
            lec_id = new String[li_s.size()];
            lecture = new String[li_s.size()];
            for(int i = 0; i < li_s.size(); i++){
                lec_id[i] = li_s.get(i);
                lecture[i] = ln_s.get(i);
            }
            
            int a = checkbtn(lecture, buttons);
            btn = new JButton[a];
            for(int i = 0; i < a; i++){
                btn[i] = buttons[i];
            }
            
            initial(lecture, btn, left, right);
            available.settext(lecture, btn);
        }

        //All
        lec_id1 = read_lec("lec_id");
        lecture1 = read_lec("username");
        JButton[] buttons1 = new JButton[]{jButton5, jButton6, jButton7, jButton8};
        if(lec_id1.length == 0){
            jLabel2.setText("No Lecture Yet");
            for(JButton button : buttons1){
                remove(button);
            }
            right1.setVisible(false);
            left1.setVisible(false);
        }else{
            int b = checkbtn(lecture1, buttons1);
            btn1 = new JButton[b];
            for(int i = 0; i < b; i++){
                btn1[i] = buttons1[i];
            }

            initial(lecture1, btn1, left1, right1);
            all.settext(lecture1, btn1);
        }
   
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        right = new javax.swing.JButton();
        left = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        right1 = new javax.swing.JButton();
        left1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        back = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("All Lecturer");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Available Now");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        right.setBackground(new java.awt.Color(153, 153, 153));
        right.setText(">");
        right.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightActionPerformed(evt);
            }
        });

        left.setBackground(new java.awt.Color(153, 153, 153));
        left.setText("<");
        left.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftActionPerformed(evt);
            }
        });

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("jButton7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("jButton8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        right1.setBackground(new java.awt.Color(153, 153, 153));
        right1.setText(">");
        right1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                right1ActionPerformed(evt);
            }
        });

        left1.setBackground(new java.awt.Color(153, 153, 153));
        left1.setText("<");
        left1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                left1ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(left)
                                .addGap(34, 34, 34)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(right))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(left1)
                                .addGap(34, 34, 34)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6)
                                .addGap(18, 18, 18)
                                .addComponent(jButton7)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(right1)))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(back)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(right)
                    .addComponent(left))
                .addGap(57, 57, 57)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(right1)
                    .addComponent(left1))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            passid(available.id(), lec_id);
        } catch (IOException ex) {
            Logger.getLogger(view_lecture.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightActionPerformed
        available.rightclick(lecture, btn, left, right);
        available.settext(lecture, btn);
    }//GEN-LAST:event_rightActionPerformed

    private void leftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftActionPerformed
        available.leftclick(lecture, btn, left, right);
        available.settext(lecture, btn);
    }//GEN-LAST:event_leftActionPerformed

    private void right1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_right1ActionPerformed
        all.rightclick(lecture1, btn1, left1, right1);
        all.settext(lecture1, btn1);
    }//GEN-LAST:event_right1ActionPerformed

    private void left1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_left1ActionPerformed
        all.leftclick(lecture1, btn1, left1, right1);
        all.settext(lecture1, btn1);
    }//GEN-LAST:event_left1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            passid(all.id(), lec_id1);
        } catch (IOException ex) {
            Logger.getLogger(view_lecture.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            passid(all.id()+3, lec_id1);
        } catch (IOException ex) {
            Logger.getLogger(view_lecture.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            passid(all.id()+1, lec_id1);
        } catch (IOException ex) {
            Logger.getLogger(view_lecture.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            passid(available.id()+1, lec_id);
        } catch (IOException ex) {
            Logger.getLogger(view_lecture.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            passid(available.id()+2, lec_id);
        } catch (IOException ex) {
            Logger.getLogger(view_lecture.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            passid(available.id()+3, lec_id);
        } catch (IOException ex) {
            Logger.getLogger(view_lecture.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            passid(all.id()+2, lec_id1);
        } catch (IOException ex) {
            Logger.getLogger(view_lecture.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        stu_home gui = new stu_home(ID);
        gui.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_lecture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_lecture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_lecture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_lecture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_lecture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton left;
    private javax.swing.JButton left1;
    private javax.swing.JButton right;
    private javax.swing.JButton right1;
    // End of variables declaration//GEN-END:variables
}
